sudo: false
language: php

php:
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/
  - ./vendor/bin/phpcs --standard=PSR2 ./test/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
